modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="too_many_koopers_mod"
version="1.0.0"
displayName="Too Many Koopers Mod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="skrumpus, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.too_many_koopers_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



